# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-05 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_control_app', '0002_subject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'subject_images'),
        ),
    ]
