# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-06 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_control_app', '0004_auto_20181205_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='theme',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
