# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-06 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_control_app', '0005_activity_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='date',
        ),
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
