# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-06 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_control_app', '0006_auto_20181206_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='activity',
        ),
        migrations.AddField(
            model_name='activity',
            name='classroom_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Curriculum',
        ),
    ]
